objects/Account.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <description>Person Age</description>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Birth_Date__c</fullName>
        <label>Birth Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Children__c</fullName>
        <label>Children</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>InsuredTobaccoConsumption__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Within the last 5 years, has the proposed insured used any form of Tobacco or Nicotine?</description>
        <inlineHelpText>Within the last 5 years, has the proposed insured used any form of Tobacco or Nicotine?</inlineHelpText>
        <label>InsuredTobaccoConsumption</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Insuredflownaircraft__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has the proposed Insured flown on an aircraft as a pilot or crew member in the past 2 years, or any such flights planned in the future?</description>
        <inlineHelpText>Has the proposed Insured flown on an aircraft as a pilot or crew member in the past 2 years, or any such flights planned in the future?</inlineHelpText>
        <label>Insuredflownaircraft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LifeDisabilityInsurance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has the proposed Insured or even had a  request for Life or Disability Insurance Declined, Rated, Cancelled, or Restricted in Any way?</description>
        <inlineHelpText>Has the proposed Insured or even had a  request for Life or Disability Insurance Declined, Rated, Cancelled, or Restricted in Any way?</inlineHelpText>
        <label>LifeDisabilityInsurance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Marital_Status__c</fullName>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Married</fullName>
                </value>
                <value>
                    <fullName>Single</fullName>
                </value>
                <value>
                    <fullName>Engaged</fullName>
                </value>
                <value>
                    <fullName>Separated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <label>Middle Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occupation__c</fullName>
        <label>Occupation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <label>Tax ID</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>(TODAY()-  D_O_B__c  )/365.2425</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City.</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Coverage__c</fullName>
        <label>Coverage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$50,000 - $70,000</fullName>
                </value>
                <value>
                    <fullName>$70,001 - $100,000</fullName>
                </value>
                <value>
                    <fullName>$100,001 - $200,000</fullName>
                </value>
                <value>
                    <fullName>$200,001 - $250,000</fullName>
                </value>
                <value>
                    <fullName>$250,001 - $399,000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>D_O_B__c</fullName>
        <label>D.O.B.</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Facebook_Profile_URL__c</fullName>
        <label>Facebook Profile URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interest__c</fullName>
        <label>Interest</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address__c</fullName>
        <label>Mailing Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marital_Status__c</fullName>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Married</fullName>
                </value>
                <value>
                    <fullName>Single</fullName>
                </value>
                <value>
                    <fullName>Engaged</fullName>
                </value>
                <value>
                    <fullName>Separated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <label>Middle Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occupation__c</fullName>
        <label>Occupation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other__c</fullName>
        <label>Other</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_contact_time__c</fullName>
        <label>Preferred contact time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>6am - 9am</fullName>
                </value>
                <value>
                    <fullName>9am -12pm</fullName>
                </value>
                <value>
                    <fullName>12pm - 4pm</fullName>
                </value>
                <value>
                    <fullName>4pm - 6pm</fullName>
                </value>
                <value>
                    <fullName>6 pm - 9pm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Interest__c</fullName>
        <label>Product Interest</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rider__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rider</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <label>Tax ID</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term_Length__c</fullName>
        <label>Term Length</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>intial_premium__c</fullName>
        <label>intial premium</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Cover_Amount__c</fullName>
        <label>Cover Amount</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$50,000 - $70,000</fullName>
                </value>
                <value>
                    <fullName>$70,001 - $100,000</fullName>
                </value>
                <value>
                    <fullName>$100,001 - $200,000</fullName>
                </value>
                <value>
                    <fullName>$200,001 - $250,000</fullName>
                </value>
                <value>
                    <fullName>$250,001 - $399,000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term_Length__c</fullName>
        <label>Term Length</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Policy__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Policies</relationshipLabel>
        <relationshipName>Policies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Premium_Payment__c</fullName>
        <label>Initial Premium Payment</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Mode_Of_Payment__c</fullName>
        <label>Mode Of Payment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Online Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quote_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Policies</relationshipLabel>
        <relationshipName>Policies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SendEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SendEmail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Application Submitted</fullName>
                </value>
                <value>
                    <fullName>Policy issued</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Qualification_Status__c</fullName>
        <label>Tax Qualification Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Qualified</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <label>Payment Term</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Semi Annual</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recommended_Rider__c</fullName>
        <label>Recommended Rider</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accidental Disability</fullName>
                </value>
                <value>
                    <fullName>Waiver of Premium</fullName>
                </value>
                <value>
                    <fullName>Critical Illness</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rider__c</fullName>
        <label>Rider</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sum_Insured__c</fullName>
        <label>Sum Insured</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$50,000 - $70,000</fullName>
                </value>
                <value>
                    <fullName>$70,001 - $100,000</fullName>
                </value>
                <value>
                    <fullName>$100,001 - $200,000</fullName>
                </value>
                <value>
                    <fullName>$200,001 - $250,000</fullName>
                </value>
                <value>
                    <fullName>$250,001 - $399,000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term_Length__c</fullName>
        <label>Term Length</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QuoteGenerationCtrl.cls
public with sharing class QuoteGenerationCtrl {
    
    public Opportunity oppObj{get;set;}
    public Policy__c policyObj{get;set;}
    public String leadId{get;set;}
    public Lead leadObj{get;set;}
    public Account accList{get;set;}
    Public string ApplicationStatus{get;set;}
    Public string Accountmiddlename{get;set;}
    Public string QuotePayment{get;set;}
    public Decimal CalculatedPremium{get;set;}
    public Decimal planTerm{get;set;}
    public String coverageAmt{get;set;}
    public String selectedProduct{get;set;}
    public String selectedSumInsured{get;set;}
    public String modeOfPayement {get;set;}
    public String billingFreq{get;set;}
    public String selectedRider {get;set;}
    public String TextQus1 {get;set;}
    public String TextQus2{get;set;}
    public String TextQus3{get;set;}
    
    public QuoteGenerationCtrl(ApexPages.StandardController controller)
    {
        leadObj = (lead)Controller.getRecord();
        leadId =leadObj.id;
        
        getDetails();
    }
    
    
    public void getDetails(){
        
        String strPlid1= ApexPages.currentPage().getParameters().get('pid'); 
        List<Opportunity> oppList = [select id,AccountID,Cover_Amount__c from Opportunity where AccountID =: leadObj.ConvertedAccountId];
        List<Account> accObjs=[select id,LifeDisabilityInsurance__c,Name,Insuredflownaircraft__c,InsuredTobaccoConsumption__c from Account where id=:leadObj.convertedAccountId];
        
        if(oppList.size()>0)
        {
            oppObj =  oppList.get(0);
        }
        
        accList = [SELECT Id, BillingState, ShippingState,BillingCity ,Height__c ,weight__c,PersonEmail,phone,
                   BillingPostalCode,BillingCountry,BillingStreet,Marital_Status__c ,FirstName, 
                   LastName, Birth_Date__c, Gender__c, Age__c, Tax_ID__c FROM Account where id =: leadObj.ConvertedAccountId];
        
        List<Policy__c> policyList = [SELECT Id, Name, Account_Name__r.Middle_Name__c,Quote_Name__r.Payment_Term__c,Quote_Name__r.Recommended_Rider__c ,Quote_Name__r.Sum_Insured__c, Quote_Name__r.Term_Length__c, 
                                      Initial_Premium_Payment__c, Mode_Of_Payment__c, Tax_Qualification_Status__c, SendEmail__c,
                                      Status__c FROM Policy__c where Account_Name__c =: leadObj.convertedAccountId and id =: strPlid1];
        
        if(policyList.size()>0)
        {
            policyObj =  policyList.get(0);
        }
        List<lead> leadLst =[Select id,Name,Address,country,postalCode,Tax_ID__c,Height__c,Interest__c ,Preferred_contact_time__c,Middle_Name__c,state,street,Weight__c,Term_Length__c,OwnerId,Age__c,Rider__c,Facebook_Profile_URL__c ,intial_premium__c,
                             coverage__c,City,status,City__c,Mailing_Address__c,AnnualRevenue,Occupation__c,
                             Product_Interest__c,Other__c,Phone,Marital_Status__c,Email,D_O_B__C,Children__c,Facebook_ID__c,
                             ProspectProfilePictureDocId__c,Social_Security_Number__c,Gender__c,Salutation,FirstName,
                             LastName,convertedAccountId,convertedOpportunityId,Tobacco_nicotine_use__c,Reference_Number__c 
                             From Lead where id =:leadId];
        if(leadLst.size()>0)
        {
            LeadObj =  leadLst.get(0);
        }
        ApplicationStatus = policyObj.Status__c;
        Accountmiddlename = policyObj.Account_Name__r.Middle_Name__c;
        QuotePayment = policyObj.Quote_Name__r.Payment_Term__c;
        CalculatedPremium = policyObj.Initial_Premium_Payment__c;
        planTerm = policyObj.Quote_Name__r.Term_Length__c;
        //selectedModeOfPayment = policyObj[0].Mode_Of_Payment__c;
        selectedSumInsured=policyObj.Quote_Name__r.Sum_Insured__c;
        selectedProduct = 'Term';
        modeOfPayement = policyObj.Mode_Of_Payment__c;
        billingFreq = policyObj.Quote_Name__r.Payment_Term__c;
        selectedRider = policyObj.Quote_Name__r.Recommended_Rider__c;
        //if(leadObj.rider__c) selectedRider ='Critical Illness';else selectedRider ='None';  
        if(oppList.size() > 0)
        {
            coverageAmt = oppObj.Cover_Amount__c;
        }
        if(accObjs[0].LifeDisabilityInsurance__c == true){
            TextQus1 = 'Yes';
        }
        else{
            TextQus1 = 'No';
        }
        if(accObjs[0].Insuredflownaircraft__c == true){
            TextQus2 = 'Yes';
        }
        else{
            TextQus2 = 'No';
        }
        if(accObjs[0].InsuredTobaccoConsumption__c == true){
            TextQus3 = 'Yes';
        }
        else{
            TextQus3 = 'No';
        }
    }
    public String leadAdd{get{
        
        String addr='';
        addr=leadObj.street==null?'':leadObj.street+', ';
        addr=addr+(leadObj.city==null?'':leadObj.city+', ');
        addr=addr+(leadObj.state==null?'':leadObj.state+', ');
        addr=addr+(leadObj.PostalCode==null?'':leadObj.PostalCode+', ');
        addr=addr+(leadObj.country==null?'':leadObj.country);
        
        addr = addr.removeEnd(',');
        
        return addr;
    }
                          set;}
}