objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Rider__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rider</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Term_Length__c</fullName>
        <label>Term Length</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Premium__c</fullName>
        <label>Premium</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Term_Length__c</fullName>
        <label>Term Length</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <label>Payment Term</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Semi Annual</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Premium__c</fullName>
        <label>Premium</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recommended_Rider__c</fullName>
        <label>Recommended Rider</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accidental Disability</fullName>
                </value>
                <value>
                    <fullName>Waiver of Premium</fullName>
                </value>
                <value>
                    <fullName>Critical Illness</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rider__c</fullName>
        <label>Rider</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sum_Insured__c</fullName>
        <label>Sum Insured</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$50,000 - $70,000</fullName>
                </value>
                <value>
                    <fullName>$70,001 - $100,000</fullName>
                </value>
                <value>
                    <fullName>$100,001 - $200,000</fullName>
                </value>
                <value>
                    <fullName>$200,001 - $250,000</fullName>
                </value>
                <value>
                    <fullName>$250,001 - $399,000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term_Length__c</fullName>
        <label>Term Length</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tobacco_Nicotine__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tobacco/Nicotine</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QuoteEmailTempalteController.cls
public without sharing class QuoteEmailTempalteController {
  public Lead leadobj {get;set;}
  public Quote lquotes {get;set;}
   
    public QuoteEmailTempalteController() {
        lquotes = New Quote();
        String OppId = apexpages.currentpage().getparameters().get('id'); 
        lquotes = [Select id,Account.PersonEmail,Opportunity.Name,Recommended_Rider__c, account.name, Payment_Term__c,Premium__c, Product__c, Rider__c, Sum_Insured__c, Term_Length__c, Tobacco_Nicotine__c from Quote where OpportunityId = :OppId Order by QuoteNumber desc limit 1] ;
        String email = lquotes.Account.PersonEmail;
    } 
       public String getTobacco(){
           string tob;
            if(lquotes.Tobacco_Nicotine__c == true){
                tob = 'Yes';
                }
            else{
               tob = 'No';
                }
            return tob;
     }
}